INSERT INTO DatabaseType
  (table_name, name, emoji, description)
VALUES
  ('HisyeoWord', 'vrb', '⭕', 'Verbs are the action or state that is at the center of the predicate.'),
  ('HisyeoWord', 'nom', '🔺', 'Nouns are the subjects, objects and thematic items/concepts/things that are introduced by prepositions into a sentence.'),
  ('HisyeoWord', 'adj', '🔷', 'Adjectives are words that follow a head noun or preposition and modify the meaning of the connected noun or predicate in certain ways.'),
  ('HisyeoWord', 'det', '🟧', 'Determiners precede the head noun of a noun phrase and classify them in certain ways.'),
  ('HisyeoWord', 'prep', '🟢', 'Prepositions precede noun phrases and connect them to the predicate in certain ways.'),
  ('HisyeoWord', 'prn', '🔼', 'Pronouns are shortcuts that you can use to refer to people or things that you are talking to or about.'),
  ('HisyeoWord', 'part', '⚡', 'Particles are special words that change the interpretation of prepositions, verbs, and nouns.'),
  ('HisyeoWord', 'num', '🔢', 'Numerals are special determiners that represent numerical quantities.'),
  ('HisyeoWord', 'conj', '❌', 'Conjunctions are particles that glue sentences or noun phrases together in certain ways.'),
  ('HisyeoWord', 'post', '⭐', 'Postpositions are sentence ending particles that modify the sentence in certain ways.'),
  ('HisyeoWord', 'inter', '❗', 'Interjections are single word sentences.'),
  ('HisyeoWord', 'punct', '❗', 'Interjections are single word sentences.'),
  ('HisyeoWord', 'grp', '📋', 'Grouping marks surround direct quotations, sidenotes or other notations.'),
  ('Kenning', 'fix', '🛠️', 'Fixes are needed for this kenning before it can be published.'),
  ('Kenning', 'review', '👀', 'Review is needed of this kenning to confirm correct spelling, grammar and code of conduct compliance.'),
  ('Kenning', 'del', '⛔', 'Deleted kennings are not available to see on the site or receive via the Discord bot.'),
  ('Kenning', 'publ', '🚢', 'Published kennings are available to see on the site or recieve via the Discord bot.'),
  ('UserVote', 'std', '⭐', 'Standard expression that is precise, succint, and understandable.'),
  ('UserVote', 'min', '🟨', 'Minimalist expression which is true but vague or easily misconstrued.'),
  ('UserVote', 'appr', '👍', 'Approving expression showing approval or admiration.'),
  ('UserVote', 'arch', '🏛️', 'Archaic or antiquated phrasing that is no longer in ordinary use.'),
  ('UserVote', 'dial', '🌍', 'Dialectal expression which is mainly used in particular regions.'),
  ('UserVote', 'disappr', '👎', 'Disapproving expression showing disapproval or contempt.'),
  ('UserVote', 'fig', '🎭', 'Figurative expression using non-literal or metaphorical phrasing.'),
  ('UserVote', 'form', '📜', 'Formal expression only used in serious or official language, not appropriate in normal everyday conversation.'),
  ('UserVote', 'hum', '🤣', 'Humorous expression intended to be funny.'),
  ('UserVote', 'inf', '👥', 'Informal expression used between friends or in a relaxed or unofficial situation, not appropriate for formal situations.'),
  ('UserVote', 'lit', '📖', 'Literary language used mainly in literature, e.g., poems and novels.'),
  ('UserVote', 'off', '🚫', 'Offensive expression refering to people in a way that is very insulting, especially in connection with their race, religion, sex or disabilities.'),
  ('UserVote', 'sl', '🏄', 'Slang unique to people who share the same interests or belong to the same social group.'),
  ('UserVote', 'spec', '🔬', 'Specialist language used by people who specialize in particular subject areas.'),
  ('UserVote', 'taboo', '💀', 'Taboo expression thought to be shocking by many people and not to be used.');